version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gomodguard
    - mnd
    - noinlineerr
    - tagliatelle
    - testableexamples
    - testpackage
    - varnamelen
    - wsl
  exclusions:
    rules:
      # Exclude some linters on test code
      - path: _test\.go
        linters:
          - dupl
          - err113
          - errcheck
          - errchkjson
          - gochecknoglobals
          - goconst
          - gocyclo
          - varnamelen
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: indent-error-flow
        - name: time-naming
        - name: unexported-return
        - name: var-naming
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/robmyersrobmyers/oci-configs
